# -*- mode: python ; coding: utf-8 -*-

a = Analysis(
    ["main.py"],
    pathex=[],
    binaries=[],
    datas=[
        ("assets", "assets"),
        ("logo.png", "."),
        ("logo.ico", "."),
        ("cloudflare", "cloudflare"),
        ("VERSION", "."),
        ("vendor/rustdesk", "vendor/rustdesk"),
    ],
    hiddenimports=[
        "screenshot_app",
        "screenshot_ui",
        "gdrive_client",
        "screen_recorder",
        "recorder_ui",
        "p2p_transfer",
        "p2p_ui",
        "lan_share",
        "lan_ui",
        "cleaner",
        "cleaner_ui",
        "lyrics_engine",
        "lyrics_ui",
        "download_queue",
        "productivity",
        "simple_boards",
        "alarm_ui",
        "alarm_sounds",
        "notebook_store",
        "notebook_ui",
        "notebook_sync",
        "ui_theme",
        "theme",
        "updater",
        "storage",
        "skin",
        "hotkeys",
        "hub_ui",
        "float_assistant",
        "win_topmost",
        "rustdesk_bridge",
        "remote_ui",
        "voice",
        "autostart",
        "weather",
        "notebook_store",
        "notebook_ui",
        "notebook_sync",
        "file_organizer",
        "file_organizer_ui",
        "mss",
        "imageio_ffmpeg",
        "websockets",
        "cv2",
        "numpy",
        "sounddevice",
        "PyQt6.QtMultimedia",
        "win32com",
        "win32com.client",
        "pythoncom",
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        "torch",
        "tensorflow",
        "matplotlib",
        "scipy",
        "IPython",
        "jupyter",
    ],
    noarchive=False,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name="DesktopToolkit",
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    console=False,
    disable_windowed_traceback=False,
    icon="logo.ico",
)
coll = COLLECT(
    exe,
    a.binaries,
    a.datas,
    strip=False,
    upx=True,
    upx_exclude=[],
    name="DesktopToolkit",
)
